server:
  port: 8081
  
spring:
  main:
    allow-bean-definition-overriding: true
    
camel:
  component:
    rabbitmq:
      hostname: localhost
      port-number: 5672
      username: admin
      password: admin
  springboot:
    main-run-controller: true

rabbitmq:
  camel:
    producer:
      uri: 
        main: rabbitmq:ex-employee?connectionFactory=#rabbitConnectionFactory&queue=queue-employee-main&routingKey=queue-employee-main&autoDelete=false&guaranteedDeliveries=true&mandatory=true
#        dead: rabbitmq:ex-employee?connectionFactory=#rabbitConnectionFactory&queue=queue-employee-dead&routingKey=queue-employee-dead&autoDelete=false  